# Generated by Django 5.0.7 on 2025-10-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_more_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('customer', 'Khách hàng'), ('employee', 'Nhân viên'), ('manager', 'Quản lý')], db_index=True, default='employee', help_text='Loại người dùng', max_length=20),
        ),
    ]
