# Generated by Django 5.2.7 on 2025-10-24 04:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='Ngày làm việc')),
                ('attendance_type', models.CharField(choices=[('full', 'Làm cả ngày'), ('half', 'Làm nửa ngày'), ('off', 'Nghỉ')], default='full', help_text='Loại chấm công', max_length=10)),
                ('check_in_time', models.TimeField(blank=True, help_text='Giờ vào', null=True)),
                ('check_out_time', models.TimeField(blank=True, help_text='Giờ ra', null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Nhân viên', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chấm công',
                'verbose_name_plural': 'Chấm công',
                'db_table': 'attendances',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='attendances_user_id_e63f54_idx'), models.Index(fields=['date'], name='attendances_date_234e8d_idx'), models.Index(fields=['attendance_type'], name='attendances_attenda_e31699_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
