# Generated by Django 5.2.7 on 2025-10-27 09:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0010_orderitem_estimated_weight_range_and_more'),
        ('users', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('income', 'Thu'), ('expense', 'Chi')], db_index=True, help_text='Loại giao dịch: Thu/Chi', max_length=10)),
                ('category', models.CharField(choices=[('sales', 'Doanh thu bán hàng'), ('other_income', 'Thu nhập khác'), ('purchase', 'Mua hàng'), ('salary', 'Lương nhân viên'), ('rent', 'Thuê mặt bằng'), ('utilities', 'Tiền điện nước'), ('marketing', 'Marketing'), ('shipping', 'Vận chuyển'), ('maintenance', 'Bảo trì'), ('other_expense', 'Chi phí khác')], help_text='Danh mục', max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, help_text='Số tiền (VNĐ)', max_digits=15)),
                ('date', models.DateField(db_index=True, help_text='Ngày giao dịch')),
                ('description', models.TextField(help_text='Mô tả chi tiết')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú thêm', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, help_text='Đơn hàng (nếu là doanh thu từ bán hàng)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='seafood.order')),
            ],
            options={
                'verbose_name': 'Giao dịch',
                'verbose_name_plural': 'Giao dịch',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_type', 'date'], name='transaction_transac_d48df4_idx'), models.Index(fields=['category'], name='transaction_categor_45fcdd_idx'), models.Index(fields=['date'], name='transaction_date_7edf95_idx')],
            },
        ),
    ]
