# Generated by Django 5.2.7 on 2025-10-21 14:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('messenger', 'Messenger'), ('phone', 'Điện thoại'), ('market', 'Chợ'), ('company', 'Công ty'), ('other', 'Khác')], max_length=20)),
                ('contact_info', models.JSONField(blank=True, default=dict, help_text='Thông tin liên hệ: phone, facebook_url, zalo_id...')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'import_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Seafood',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('current_price', models.DecimalField(decimal_places=0, help_text='Giá hiện tại/kg (VNĐ)', max_digits=12)),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Số kg còn lại trong kho', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, help_text='Nguồn gốc: Cà Mau, Phú Quốc...', max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('active', 'Đang bán'), ('inactive', 'Ngừng bán'), ('out_of_stock', 'Hết hàng')], default='active', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text="['tươi sống', 'đông lạnh', 'cao cấp']")),
            ],
            options={
                'verbose_name': 'Sản phẩm',
                'verbose_name_plural': 'Sản phẩm',
                'db_table': 'seafood',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SeafoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
                'db_table': 'seafood_category',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('batch_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('import_date', models.DateField(default=django.utils.timezone.now)),
                ('import_price', models.DecimalField(decimal_places=0, help_text='Giá nhập/kg (VNĐ)', max_digits=12)),
                ('sell_price', models.DecimalField(decimal_places=0, help_text='Giá bán/kg (VNĐ)', max_digits=12)),
                ('total_weight', models.DecimalField(decimal_places=2, help_text='Tổng kg nhập vào', max_digits=10)),
                ('remaining_weight', models.DecimalField(decimal_places=2, help_text='Số kg còn lại', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('import_details', models.JSONField(blank=True, default=dict, help_text='Link chat, hình ảnh, thông tin giao dịch')),
                ('status', models.CharField(choices=[('received', 'Đã nhận'), ('selling', 'Đang bán'), ('sold_out', 'Đã bán hết')], default='received', max_length=20)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seafood_imports', to=settings.AUTH_USER_MODEL)),
                ('import_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.importsource')),
                ('seafood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='seafood.seafood')),
            ],
            options={
                'db_table': 'import_batch',
                'ordering': ['-import_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('order_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('customer_address', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('transfer', 'Chuyển khoản'), ('momo', 'MoMo')], max_length=50)),
                ('payment_status', models.CharField(choices=[('pending', 'Chờ thanh toán'), ('paid', 'Đã thanh toán')], default='pending', max_length=20)),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Cân nặng thực tế (kg). VD: 0.5, 1.2, 3.5', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=0, help_text='Giá/kg (VNĐ)', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(blank=True, help_text='Lô hàng được bán', null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.importbatch')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='seafood.order')),
                ('seafood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='seafood.seafood')),
            ],
            options={
                'db_table': 'order_item',
            },
        ),
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag')),
                ('type', models.CharField(choices=[('import', 'Nhập hàng'), ('sale', 'Bán hàng'), ('adjust', 'Điều chỉnh'), ('loss', 'Hao hụt')], max_length=20)),
                ('weight_change', models.DecimalField(decimal_places=2, help_text='Số kg thay đổi (+ nhập, - xuất)', max_digits=10)),
                ('stock_after', models.DecimalField(decimal_places=2, help_text='Tồn kho sau khi thay đổi', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.importbatch')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seafood.orderitem')),
                ('seafood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='seafood.seafood')),
            ],
            options={
                'db_table': 'inventory_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='seafood',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seafoods', to='seafood.seafoodcategory'),
        ),
    ]
