# Generated by Django 5.2.7 on 2025-10-22 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian gửi vận chuyển', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên gửi hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipped_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_notes',
            field=models.TextField(blank=True, help_text='Ghi chú vận chuyển'),
        ),
        migrations.AddField(
            model_name='order',
            name='weighed_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian cân hàng', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weighed_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên cân hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighed_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='weight_images',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách URL ảnh cân hàng'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='estimated_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cân nặng ước tính ban đầu (kg)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight_image_url',
            field=models.URLField(blank=True, help_text='Ảnh cân của sản phẩm này', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('processing', 'Đang xử lý'), ('weighed', 'Đã cân'), ('ready', 'Sẵn sàng giao'), ('shipped', 'Đã gửi vận chuyển'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
