# Generated by Django 5.2.7 on 2025-10-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0002_order_shipped_at_order_shipped_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Số lượng (con/thùng). VD: 10 con ốc, 2 thùng tôm', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seafood',
            name='avg_unit_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Trọng lượng trung bình mỗi con/thùng (kg). VD: mỗi con ốc 0.05kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='seafood',
            name='unit_type',
            field=models.CharField(choices=[('kg', 'Kilogram (kg)'), ('piece', 'Con/Cái'), ('box', 'Thùng/Hộp')], default='kg', help_text='Đơn vị tính: kg, con, thùng', max_length=20),
        ),
    ]
