# Generated by Django 5.2.7 on 2025-10-23 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0003_orderitem_quantity_seafood_avg_unit_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Chưa thanh toán'), ('pending_verification', 'Chờ xác minh'), ('paid', 'Đã thanh toán')], default='pending', max_length=20),
        ),
    ]
