# Generated by Django 5.2.7 on 2025-10-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0004_update_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_source',
            field=models.CharField(blank=True, choices=[('telephone', 'Điện thoại'), ('facebook', 'Facebook'), ('zalo', 'Zalo')], help_text='Nguồn khách hàng', max_length=20),
        ),
    ]
