# Generated by Django 5.2.7 on 2025-10-24 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0006_order_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian giao cho nhân viên kho', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_employee',
            field=models.ForeignKey(blank=True, help_text='Nhân viên kho được giao cân hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='confirmed_by_sale_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian Sale xác nhận', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='sale_user',
            field=models.ForeignKey(blank=True, help_text='Sale phụ trách đơn hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('pending_sale_confirm', 'Chờ Sale xác nhận'), ('confirmed', 'Đã xác nhận'), ('assigned_to_warehouse', 'Đã giao cho kho'), ('weighing', 'Đang cân'), ('weighed', 'Đã cân xong'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='weighed_at',
            field=models.DateTimeField(blank=True, help_text='Thời gian cân hàng xong', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='weighed_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên đã cân hàng', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weighed_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
