# Generated by Django 5.2.7 on 2025-10-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0007_order_assigned_at_order_assigned_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản (VietQR)'), ('cod', 'Tiền khi nhận hàng'), ('transfer', 'Chuyển khoản'), ('momo', 'MoMo')], max_length=50),
        ),
    ]
