# Generated by Django 5.2.7 on 2025-10-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seafood', '0009_add_delivered_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='estimated_weight_range',
            field=models.CharField(blank=True, help_text="Khoảng cân ước tính customer chọn. VD: '2-3.5kg', '1-2kg'", max_length=50),
        ),
        migrations.AddField(
            model_name='seafood',
            name='weight_range_options',
            field=models.JSONField(blank=True, default=list, help_text="Các khoảng cân khách có thể chọn. VD: ['0.5-1kg', '1-2kg', '2-3.5kg']"),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cân nặng thực tế (kg). VD: 0.5, 1.2, 3.5. NULL = chưa cân', max_digits=10, null=True),
        ),
    ]
