# Generated by Django 5.0.7 on 2025-10-21 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Department manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rbac.department'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module'], name='rbac_permis_module_132e53_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename'], name='rbac_permis_codenam_64fe17_idx'),
        ),
        migrations.AddField(
            model_name='department',
            name='default_role',
            field=models.ForeignKey(blank=True, help_text='Default role for members', null=True, on_delete=django.db.models.deletion.SET_NULL, to='rbac.role'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='User who granted this permission', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(help_text='Assigned permissions', related_name='roles', through='rbac.RolePermission', to='rbac.permission'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='User who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='rbac.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role'], name='rbac_user_r_user_id_cd1ec7_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='rbac_user_r_expires_dfa993_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
