# Generated by Django 5.2.7 on 2025-10-24 05:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(help_text='Năm')),
                ('month', models.IntegerField(help_text='Tháng')),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Lương cơ bản', max_digits=12)),
                ('working_days', models.DecimalField(decimal_places=1, help_text='Số ngày công thực tế', max_digits=5)),
                ('standard_working_days', models.IntegerField(default=26, help_text='Số ngày làm việc chuẩn')),
                ('actual_base_salary', models.DecimalField(decimal_places=2, help_text='Lương cơ bản thực tế (theo ngày công)', max_digits=12)),
                ('attendance_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp chuyên cần', max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp xăng xe', max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp ăn trưa', max_digits=10)),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp điện thoại', max_digits=10)),
                ('total_allowances', models.DecimalField(decimal_places=2, default=0, help_text='Tổng phụ cấp', max_digits=12)),
                ('sales_commission', models.DecimalField(decimal_places=2, default=0, help_text='Thưởng doanh số', max_digits=12)),
                ('sales_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Doanh thu tháng', max_digits=15)),
                ('kpi_score', models.DecimalField(decimal_places=2, default=0, help_text='Điểm KPI (0-100)', max_digits=5)),
                ('kpi_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Thưởng KPI', max_digits=10)),
                ('other_bonus', models.DecimalField(decimal_places=2, default=0, help_text='Thưởng khác', max_digits=10)),
                ('total_bonuses', models.DecimalField(decimal_places=2, default=0, help_text='Tổng thưởng', max_digits=12)),
                ('gross_salary', models.DecimalField(decimal_places=2, help_text='Tổng thu nhập (trước thuế, BH)', max_digits=12)),
                ('social_insurance', models.DecimalField(decimal_places=2, default=0, help_text='BHXH (8%)', max_digits=10)),
                ('health_insurance', models.DecimalField(decimal_places=2, default=0, help_text='BHYT (1.5%)', max_digits=10)),
                ('unemployment_insurance', models.DecimalField(decimal_places=2, default=0, help_text='BHTN (1%)', max_digits=10)),
                ('total_insurance', models.DecimalField(decimal_places=2, default=0, help_text='Tổng bảo hiểm', max_digits=10)),
                ('taxable_income', models.DecimalField(decimal_places=2, default=0, help_text='Thu nhập chịu thuế', max_digits=12)),
                ('personal_deduction', models.DecimalField(decimal_places=2, default=11000000, help_text='Giảm trừ bản thân', max_digits=10)),
                ('dependent_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Giảm trừ người phụ thuộc', max_digits=10)),
                ('personal_income_tax', models.DecimalField(decimal_places=2, default=0, help_text='Thuế TNCN', max_digits=10)),
                ('advance_payment', models.DecimalField(decimal_places=2, default=0, help_text='Tạm ứng', max_digits=10)),
                ('penalty', models.DecimalField(decimal_places=2, default=0, help_text='Phạt', max_digits=10)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, help_text='Khấu trừ khác', max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, help_text='Tổng khấu trừ', max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, help_text='Lương thực lĩnh', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Nháp'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('paid', 'Đã thanh toán'), ('cancelled', 'Đã hủy')], default='draft', help_text='Trạng thái', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú', null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Người duyệt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='Người tạo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payrolls', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='Nhân viên', on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bảng lương',
                'verbose_name_plural': 'Bảng lương',
                'db_table': 'payrolls',
                'ordering': ['-year', '-month', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjustment_type', models.CharField(choices=[('bonus', 'Thưởng'), ('deduction', 'Khấu trừ')], help_text='Loại điều chỉnh', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Số tiền', max_digits=10)),
                ('reason', models.TextField(help_text='Lý do')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(help_text='Bảng lương', on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='payroll.payroll')),
            ],
            options={
                'verbose_name': 'Điều chỉnh lương',
                'verbose_name_plural': 'Điều chỉnh lương',
                'db_table': 'payroll_adjustments',
            },
        ),
        migrations.CreateModel(
            name='SalaryConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, help_text='Lương cơ bản (VND)', max_digits=12)),
                ('standard_working_days', models.IntegerField(default=26, help_text='Số ngày làm việc chuẩn trong tháng')),
                ('attendance_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp chuyên cần (đi đủ công)', max_digits=10)),
                ('transportation_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp xăng xe', max_digits=10)),
                ('meal_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp ăn trưa', max_digits=10)),
                ('phone_allowance', models.DecimalField(decimal_places=2, default=0, help_text='Phụ cấp điện thoại', max_digits=10)),
                ('enable_commission', models.BooleanField(default=False, help_text='Áp dụng hoa hồng doanh số')),
                ('commission_rate_1', models.DecimalField(decimal_places=2, default=1.0, help_text='Hoa hồng < 20 triệu (%)', max_digits=5)),
                ('commission_threshold_2', models.DecimalField(decimal_places=2, default=20000000, help_text='Ngưỡng bậc 2', max_digits=12)),
                ('commission_rate_2', models.DecimalField(decimal_places=2, default=1.5, help_text='Hoa hồng 20-50 triệu (%)', max_digits=5)),
                ('commission_threshold_3', models.DecimalField(decimal_places=2, default=50000000, help_text='Ngưỡng bậc 3', max_digits=12)),
                ('commission_rate_3', models.DecimalField(decimal_places=2, default=2.0, help_text='Hoa hồng 50-100 triệu (%)', max_digits=5)),
                ('commission_threshold_4', models.DecimalField(decimal_places=2, default=100000000, help_text='Ngưỡng bậc 4', max_digits=12)),
                ('commission_rate_4', models.DecimalField(decimal_places=2, default=2.5, help_text='Hoa hồng > 100 triệu (%)', max_digits=5)),
                ('kpi_bonus_amount', models.DecimalField(decimal_places=2, default=1000000, help_text='Mức thưởng KPI tối đa', max_digits=10)),
                ('social_insurance_rate', models.DecimalField(decimal_places=2, default=8.0, help_text='BHXH (%)', max_digits=5)),
                ('health_insurance_rate', models.DecimalField(decimal_places=2, default=1.5, help_text='BHYT (%)', max_digits=5)),
                ('unemployment_insurance_rate', models.DecimalField(decimal_places=2, default=1.0, help_text='BHTN (%)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(help_text='Vai trò', on_delete=django.db.models.deletion.CASCADE, related_name='salary_configs', to='rbac.role')),
            ],
            options={
                'verbose_name': 'Cấu hình lương',
                'verbose_name_plural': 'Cấu hình lương',
                'db_table': 'salary_configurations',
            },
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['user', 'year', 'month'], name='payrolls_user_id_491374_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['status'], name='payrolls_status_366245_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['year', 'month'], name='payrolls_year_abceb2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('user', 'year', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='salaryconfiguration',
            unique_together={('role', 'is_active')},
        ),
    ]
